// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MonitoringAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613192118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 51.923900000000003,
                            Longitude = 4.4699,
                            Naam = "Camera Noord",
                            Postcode = "3011AA"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 51.922499999999999,
                            Longitude = 4.4790000000000001,
                            Naam = "Camera Zuid",
                            Postcode = "3011AB"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 51.923999999999999,
                            Longitude = 4.4699999999999998,
                            Naam = "Camera Oost",
                            Postcode = "3011AC"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 51.924999999999997,
                            Longitude = 4.468,
                            Naam = "Camera West",
                            Postcode = "3011AD"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Trash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("DagCategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<double>("Temperatuur")
                        .HasColumnType("float");

                    b.Property<string>("TypeAfval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WeerOmschrijving")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WindRichting")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("Trash");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CameraId = 1,
                            Confidence = 0.84999999999999998,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 17.199999999999999,
                            TypeAfval = "Plastic",
                            WeerOmschrijving = "Licht bewolkt",
                            WindRichting = "NO"
                        },
                        new
                        {
                            Id = 2,
                            CameraId = 1,
                            Confidence = 0.92000000000000004,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 19.5,
                            TypeAfval = "Metaal",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "ZW"
                        },
                        new
                        {
                            Id = 3,
                            CameraId = 2,
                            Confidence = 0.90000000000000002,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 20.0,
                            TypeAfval = "Papier",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "Z"
                        },
                        new
                        {
                            Id = 4,
                            CameraId = 2,
                            Confidence = 0.88,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 18.5,
                            TypeAfval = "Glas",
                            WeerOmschrijving = "Bewolkt",
                            WindRichting = "O"
                        },
                        new
                        {
                            Id = 5,
                            CameraId = 3,
                            Confidence = 0.80000000000000004,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 16.0,
                            TypeAfval = "Grofvuil",
                            WeerOmschrijving = "Regenachtig",
                            WindRichting = "NW"
                        },
                        new
                        {
                            Id = 6,
                            CameraId = 3,
                            Confidence = 0.94999999999999996,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 21.0,
                            TypeAfval = "Textiel",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "Z"
                        },
                        new
                        {
                            Id = 7,
                            CameraId = 4,
                            Confidence = 0.87,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 19.0,
                            TypeAfval = "Kruidenierswaren",
                            WeerOmschrijving = "Licht bewolkt",
                            WindRichting = "O"
                        },
                        new
                        {
                            Id = 8,
                            CameraId = 4,
                            Confidence = 0.93000000000000005,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 22.0,
                            TypeAfval = "Hout",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "ZW"
                        },
                        new
                        {
                            Id = 9,
                            CameraId = 1,
                            Confidence = 0.81999999999999995,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 18.0,
                            TypeAfval = "Snoeiafval",
                            WeerOmschrijving = "Regenachtig",
                            WindRichting = "NO"
                        },
                        new
                        {
                            Id = 10,
                            CameraId = 2,
                            Confidence = 0.89000000000000001,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 20.5,
                            TypeAfval = "Batterijen",
                            WeerOmschrijving = "Licht bewolkt",
                            WindRichting = "Z"
                        },
                        new
                        {
                            Id = 11,
                            CameraId = 3,
                            Confidence = 0.91000000000000003,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 17.5,
                            TypeAfval = "Elektronica",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "O"
                        },
                        new
                        {
                            Id = 12,
                            CameraId = 4,
                            Confidence = 0.83999999999999997,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 16.5,
                            TypeAfval = "Kunststof",
                            WeerOmschrijving = "Bewolkt",
                            WindRichting = "NW"
                        },
                        new
                        {
                            Id = 13,
                            CameraId = 1,
                            Confidence = 0.85999999999999999,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 19.0,
                            TypeAfval = "Groente- en fruitafval",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "Z"
                        },
                        new
                        {
                            Id = 14,
                            CameraId = 2,
                            Confidence = 0.93999999999999995,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 21.5,
                            TypeAfval = "Restafval",
                            WeerOmschrijving = "Licht bewolkt",
                            WindRichting = "NO"
                        },
                        new
                        {
                            Id = 15,
                            CameraId = 3,
                            Confidence = 0.82999999999999996,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 18.0,
                            TypeAfval = "Papier en karton",
                            WeerOmschrijving = "Regenachtig",
                            WindRichting = "ZW"
                        },
                        new
                        {
                            Id = 16,
                            CameraId = 4,
                            Confidence = 0.90000000000000002,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 20.0,
                            TypeAfval = "Metaal en kunststof",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "O"
                        },
                        new
                        {
                            Id = 17,
                            CameraId = 1,
                            Confidence = 0.88,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 17.0,
                            TypeAfval = "Grofvuil en hout",
                            WeerOmschrijving = "Licht bewolkt",
                            WindRichting = "NW"
                        },
                        new
                        {
                            Id = 18,
                            CameraId = 2,
                            Confidence = 0.92000000000000004,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 19.5,
                            TypeAfval = "Textiel en kleding",
                            WeerOmschrijving = "Zonnig",
                            WindRichting = "Z"
                        },
                        new
                        {
                            Id = 19,
                            CameraId = 3,
                            Confidence = 0.84999999999999998,
                            DagCategorie = "Werkdag",
                            DateCollected = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 18.5,
                            TypeAfval = "Snoeiafval en takken",
                            WeerOmschrijving = "Regenachtig",
                            WindRichting = "O"
                        },
                        new
                        {
                            Id = 20,
                            CameraId = 4,
                            Confidence = 0.93000000000000005,
                            DagCategorie = "Weekend",
                            DateCollected = new DateTime(2025, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperatuur = 20.5,
                            TypeAfval = "Batterijen en accu's",
                            WeerOmschrijving = "Licht bewolkt",
                            WindRichting = "ZW"
                        });
                });

            modelBuilder.Entity("ApplicationUserRole", b =>
                {
                    b.HasOne("ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trash", b =>
                {
                    b.HasOne("Camera", "Camera")
                        .WithMany("TrashRecords")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Camera", b =>
                {
                    b.Navigation("TrashRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
