name: Build, Test and Deploy a .NET Core WebApi to Azure App Service

env:
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 9.0.x
  PUBLISH_DIRECTORY: "./out/publish"

on:
  push:
    branches:
      - main
      - deployment 
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets
        run: |
          if [ -z "${{ secrets.AZURE_WEBAPP_NAME }}" ]; then
            echo "::error::Secret AZURE_WEBAPP_NAME is missing"
            exit 1
          fi
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}" ]; then
            echo "::error::Secret AZURE_WEBAPP_PUBLISH_PASSWORD is missing"
            exit 1
          fi
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}" ]; then
            echo "::error::Secret AZURE_WEBAPP_PUBLISH_USERNAME is missing"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify directory structure
        run: |
          ls -la
          ls -la MonitoringAPI/
          ls -la MonitoringAPI.Tests/
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore MonitoringAPI.sln
        
      - name: Build
        run: dotnet build MonitoringAPI.sln --no-restore
      
      - name: Test
        run: dotnet test MonitoringAPI.Tests/MonitoringAPI.Tests.csproj --no-build --verbosity normal
      
      - name: Publish
        run: dotnet publish MonitoringAPI/MonitoringAPI.csproj --output ${{ env.PUBLISH_DIRECTORY }} --configuration Release
      
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

  deploy:
    runs-on: ubuntu-latest
    needs: [check, build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIRECTORY }}
          clean: true
