name: Build, Test and Deploy a .NET Core WebApi to Azure App Service

env:
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 9.0.x
  PUBLISH_DIRECTORY: "./out/publish"
  PROJECT_ROOT: "ATIx1.4_AI-System-Integration-Datascience-LU1/MonitoringAPI"
  SOLUTION_PATH: "ATIx1.4_AI-System-Integration-Datascience-LU1/MonitoringAPI/MonitoringAPI.sln"
  PROJECT_PATH: "ATIx1.4_AI-System-Integration-Datascience-LU1/MonitoringAPI/MonitoringAPI/MonitoringAPI.csproj"
  TEST_PROJECT_PATH: "ATIx1.4_AI-System-Integration-Datascience-LU1/MonitoringAPI/MonitoringAPI.Tests/MonitoringAPI.Tests.csproj"

on:
  push:
    branches:
      - main
      - deployment 
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if AZURE_WEBAPP_NAME exists"
        if: ${{ secrets.AZURE_WEBAPP_NAME == '' }}
        run: echo "::error::Secret AZURE_WEBAPP_NAME is missing" && exit 1
        
      - name: "Check if AZURE_WEBAPP_PUBLISH_PASSWORD exists"
        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD == '' }}
        run: echo "::error::Secret AZURE_WEBAPP_PUBLISH_PASSWORD is missing" && exit 1
        
      - name: "Check if AZURE_WEBAPP_PUBLISH_USERNAME exists"
        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME == '' }}
        run: echo "::error::Secret AZURE_WEBAPP_PUBLISH_USERNAME is missing" && exit 1
        
      - name: "Check if WEBAPI_PROJECT_NAME exists"
        if: ${{ secrets.WEBAPI_PROJECT_NAME == '' }}
        run: echo "::error::Secret WEBAPI_PROJECT_NAME is missing" && exit 1

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify directory structure
        run: |
          echo "Project root: $PROJECT_ROOT"
          ls -R $PROJECT_ROOT
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore $SOLUTION_PATH
        
      - name: Build
        run: dotnet build $SOLUTION_PATH --no-restore
      
      - name: Test
        run: dotnet test $TEST_PROJECT_PATH --no-build --verbosity normal
      
      - name: Publish
        run: dotnet publish $PROJECT_PATH --output $PUBLISH_DIRECTORY --configuration Release
      
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

  deploy:
    runs-on: ubuntu-latest
    needs: [check, build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIRECTORY }}
          clean: true
